Repository integr8ly/ansible-tower-configuration, pull requests merged in 2020-02, with the labels that each got.

#141 e2e tests
  Makefile
  README.md
  e2e_test_config.yml
  playbooks/roles/tower/tasks/bootstrap.yml
  playbooks/roles/tower/tasks/e2e_prereq.yml
  scripts/e2e.sh
Labels: approved, lgtm, size/L

#147 temp fix e2e test
  Makefile
Labels: approved, lgtm, size/XS

#148 Intly 5202
  Makefile
  openshift-ci/Dockerfile.tools
  openshift-ci/README.md
  openshift-ci/test/run
  scripts/e2e.sh
Labels: approved, lgtm, size/M

#150 cleanup properly
  scripts/e2e.sh
Labels: approved, lgtm, size/S

#97 change rootca var so it doesn't overwrite app cert var
  playbooks/roles/cluster/tasks/provision_cluster.yml
Labels: approved, lgtm, size/XS

#143 add check for cert expiration
  playbooks/roles/cluster/tasks/provision_cluster.yml
Labels: approved, lgtm, size/M

#144 Add field for customer admin password
  playbooks/roles/integreatly/templates/workflow_install_survey.json.j2
Labels: approved, lgtm, size/S

#153 Fix limits for OSD
  playbooks/roles/tower/defaults/main.yml
  playbooks/roles/tower/tasks/installation.yml
  playbooks/roles/tower/templates/installation_vars.yml.j2
Labels: approved, lgtm, size/M
